services:
  - type: web
    name: finances-app
    env: docker
    plan: free
    branch: master
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromService:
          name: finances-db
          property: connectionString

  - type: postgres
    name: finances-db
    plan: free
    databaseName: finances
