[client]
showErrorDetails = false
showWarningOnDirectExecution = false

[server]
headless = true
runOnSave = false
enableXsrfProtection = true
enableCORS = true

[theme]
base = "dark"
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#c9d1d9"
font = "sans serif"

[logger]
level = "info"

[browser]
gatherUsageStats = false
